#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
picom &
/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &
dunst &
~/.config/polybar/launch.sh &
#xautolock -time 10 -locker "i3lock -i ~/Wallpapers/b33.jpg" &
xrandr --output HDMI-0 --primary --mode 1920x1080 -r 144 --left-of DP-5 --pos 0x0 &
xrandr --output DP-5 --mode 1366x768 -r 60 --right-of HDMI-0 --pos 1920x0 &
feh --bg-fill ~/Wallpapers/b33.jpg &
discord &
slack &
spotify &
solaar &
#(sleep 1 && solaar &) &
#(sleep 3 && xdotool search --onlyvisible --class "solaar" windowclose) &

bspc monitor HDMI-0 -d 火 キ 空 死
bspc monitor DP-5 -d 祖 ち ツ な

bspc config top_padding         30
bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.65
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color "#f7768e"
bspc config normal_border_color "#414868"

bspc rule -a Alacritty follow=on focus=on
bspc rule -a firefox desktop='^2'
bspc rule -a Code desktop='^3'
bspc rule -a discord desktop='^5' state=floating
bspc rule -a spotify desktop='^4' state=floating focus=off
bspc rule -a slack desktop='^5' state=floating
bspc rule -a Solaar desktop='^8' state=floating focus=off
bspc rule -a Pavucontrol state=floating
